In [1]:
import numpy as np
import pandas as pd

In [2]:
msg = pd.read_csv("messages.csv") # Time
order = pd.read_csv("orders.csv") # Date

In [3]:
msg.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [4]:
msg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [5]:
order.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [6]:
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

# Working with Dates

In [7]:
# The first thing is to convert the date/time columns into date/time datatype
order.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [8]:
order["date"] = pd.to_datetime(order["date"])

In [9]:
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [10]:
# Extract Year
order["year"] = order["date"].dt.year
order.head()

        date  product_id  city_id  orders  year
0 2019-12-10        5628       25       3  2019
1 2018-08-15        3646       14     157  2018
2 2018-10-23        1859       25       1  2018
3 2019-08-17        7292       25       1  2019
4 2019-01-06        4344       25       3  2019

In [11]:
# Extract Month
order["month"] = order["date"].dt.month
order.head()

        date  product_id  city_id  orders  year  month
0 2019-12-10        5628       25       3  2019     12
1 2018-08-15        3646       14     157  2018      8
2 2018-10-23        1859       25       1  2018     10
3 2019-08-17        7292       25       1  2019      8
4 2019-01-06        4344       25       3  2019      1

In [12]:
# Extract month name
order["month_name"] = order["date"].dt.month_name()
order.head()

        date  product_id  city_id  orders  year  month month_name
0 2019-12-10        5628       25       3  2019     12   December
1 2018-08-15        3646       14     157  2018      8     August
2 2018-10-23        1859       25       1  2018     10    October
3 2019-08-17        7292       25       1  2019      8     August
4 2019-01-06        4344       25       3  2019      1    January

In [13]:
# Extract Days (which day of the month?)
order["day_of_month"] = order["date"].dt.day
order.head()

,date,product_id,city_id,orders,year,month,month_name,day_of_month
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [14]:
# Day of week - (Which day of week?)
order["day_of_week"] = order["date"].dt.dayofweek
order.head()

,date,product_id,city_id,orders,year,month,month_name,day_of_month,day_of_week
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [15]:
# Day of the week (name)
order["name_day_of_week"] = order["date"].dt.day_name()
order.head()

,date,product_id,city_id,orders,year,month,month_name,day_of_month,day_of_week,name_day_of_week
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

In [16]:
# Extract Time elapsed between two dates
import datetime

today = datetime.datetime.today()
today

datetime.datetime(2025, 11, 25, 16, 17, 9, 991114)

In [17]:
today - order["date"]

0     2177 days 16:17:09.991114
1     2659 days 16:17:09.991114
2     2590 days 16:17:09.991114
3     2292 days 16:17:09.991114
4     2515 days 16:17:09.991114
                 ...
995   2605 days 16:17:09.991114
996   2546 days 16:17:09.991114
997   2394 days 16:17:09.991114
998   2459 days 16:17:09.991114
999   2233 days 16:17:09.991114
Name: date, Length: 1000, dtype: timedelta64[ns]

# Time

In [18]:
msg.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [19]:
msg["date"] = pd.to_datetime(msg["date"])

In [20]:
# Hour
msg["Hour"] = msg["date"].dt.hour
# Minute
msg["Minute"] = msg["date"].dt.minute
# Second
msg["Second"] = msg["date"].dt.second

msg.head()

,date,msg,Hour,Minute,Second
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [21]:
# Extract Time part
msg["time"] = msg["date"].dt.time
msg.head()

,date,msg,Hour,Minute,Second,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00