In [37]:
# Step 1 - Import the necessary libraries
import numpy as np
import pandas as pd

In [38]:
# Step 2 and 3: Import the dataset and assign it to a variable called chipo
chipo = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep="\t")

In [39]:
# Step 4: See the first 10 entries
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [40]:
# Step 5: What is the number of observations in the dataset?
chipo.shape[0]

4622

In [41]:
# Step 6: What is the number of columns in the dataset?
chipo.shape[1]

5

In [42]:
# Step 7: Print the name of all the columns.
print(chipo.columns)

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [43]:
# Step 8: How is the dataset indexed?
chipo.index

RangeIndex(start=0, stop=4622, step=1)

In [44]:
# Step 9: Which was the most-ordered item?
c = chipo.groupby("item_name")["quantity"].sum().sort_values(ascending=False)
c.head(1)

item_name
Chicken Bowl    761
Name: quantity, dtype: int64

In [45]:
# Step 10: For the most-ordered item, how many items were ordered?
c = chipo.groupby("item_name")["quantity"].sum().sort_values(ascending=False)
c.head(1)

item_name
Chicken Bowl    761
Name: quantity, dtype: int64

In [46]:
# Step 11: What was the most ordered item in the choice_description column?
chipo["choice_description"].value_counts().sort_values(ascending=False).head(1)

choice_description
[Diet Coke]    134
Name: count, dtype: int64

In [47]:
# Step 12: How many items were ordered in total?
print(chipo["quantity"].sum())

4972

In [48]:
# Step 13: Turn the item price into a float

# lambda is an anonymous function that takes in a value (e.g "$2.50") and removes the first character, then converts it into a floating number. SO the purpose is to remove the dollar sign
dollarizer = lambda x: float(x[1:])

# .apply applies the dollarizer function to every element in the item_price columns
chipo["item_price"] = chipo["item_price"].apply(dollarizer)
chipo["item_price"]

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

In [49]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 180.7+ KB

In [50]:
# Step 14: How much was the revenue for the period in the dataset?
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [54]:
revenue = (chipo["quantity"] * chipo["item_price"]).sum()
print(f"Revenue was: ${revenue}")

Revenue was: $39237.02

In [57]:
# Step 15: How many orders were made in the period?
x = chipo["order_id"].value_counts().count()
x

np.int64(1834)

In [60]:
# Step 16: What is the average revenue amount per order?
average_revenue_amount = revenue / x
print(f"Average Revenue amount is: ${average_revenue_amount:.2f}")

Average Revenue amount is: $21.39

In [62]:
# Step 17: How many different items are sold?
chipo["item_name"].nunique()

50