In [2]:
import numpy as np
import pandas as pd

## Value_counts()

In [3]:
marks = pd.DataFrame([
    [100,80,10],
    [90,70,7],
    [120,100,14],
    [80,70,14],
    [80,70,14]
],columns=['iq','marks','package'])

marks

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     70       14
4   80     70       14

In [4]:
marks.value_counts()

iq   marks  package
80   70     14         2
90   70     7          1
100  80     10         1
120  100    14         1
Name: count, dtype: int64

In [5]:
ipl = pd.read_csv("D:/Complete DataScience/Pandas/2-Pandas/ipl-matches.csv")
ipl.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

In [6]:
# ipl["MatchNumber"].unique()

In [7]:
# Find which player has won most potm in finals and qualifiers --> Player_of_Match, MatchNumber(Qualifier 2, Qualifier 1)
ipl[ipl["MatchNumber"].isin(["Qualifier 1", "Qualifier 2", "Final", "Eliminator"])]["Player_of_Match"].value_counts()

Player_of_Match
SK Raina             3
KA Pollard           2
AB de Villiers       2
JJ Bumrah            2
YK Pathan            2
M Vijay              2
F du Plessis         1
RM Patidar           1
JC Buttler           1
HH Pandya            1
DA Miller            1
RD Gaikwad           1
VR Iyer              1
SR Watson            1
AD Russell           1
KH Pandya            1
SP Narine            1
TA Boult             1
MP Stoinis           1
KS Williamson        1
RR Pant              1
DA Warner            1
BCJ Cutting          1
Washington Sundar    1
NM Coulter-Nile      1
KV Sharma            1
MK Pandey            1
A Nehra              1
RG Sharma            1
UT Yadav             1
V Sehwag             1
Harbhajan Singh      1
BJ Hodge             1
MS Bisla             1
MEK Hussey           1
CH Gayle             1
A Kumble             1
Name: count, dtype: int64

In [8]:
# How many matches each team has played
(ipl["Team1"].value_counts() + ipl["Team2"].value_counts()).sort_values(ascending=False)

Mumbai Indians                 231
Royal Challengers Bangalore    226
Kolkata Knight Riders          223
Chennai Super Kings            208
Rajasthan Royals               192
Kings XI Punjab                190
Delhi Daredevils               161
Sunrisers Hyderabad            152
Deccan Chargers                 75
Delhi Capitals                  63
Pune Warriors                   46
Gujarat Lions                   30
Punjab Kings                    28
Gujarat Titans                  16
Rising Pune Supergiant          16
Lucknow Super Giants            15
Kochi Tuskers Kerala            14
Rising Pune Supergiants         14
Name: count, dtype: int64

# Rank (only applicable on Series) --> Compute numerical data ranks (1 through n) along axis.

In [9]:
batsman = pd.read_csv("D:/Complete DataScience/Pandas/2-Pandas/batsman_runs_ipl.csv")
batsman.head()

           batter  batsman_run
0  A Ashish Reddy          280
1        A Badoni          161
2      A Chandila            4
3        A Chopra           53
4     A Choudhary           25

In [10]:
# What is the overall rank of the batsman on the basis of runs he has scored
batsman["batsman_rank"] = batsman["batsman_run"].rank(ascending=False)
batsman.sort_values("batsman_rank")

             batter  batsman_run  batsman_rank
569         V Kohli         6634           1.0
462        S Dhawan         6244           2.0
130       DA Warner         5883           3.0
430       RG Sharma         5881           4.0
493        SK Raina         5536           5.0
..              ...          ...           ...
570  V Pratap Singh            0         594.0
63     Abdur Razzak            0         594.0
562          U Kaul            0         594.0
65       Akash Deep            0         594.0
57           AS Roy            0         594.0

[605 rows x 3 columns]

# Missing data Handling

In [11]:
students = pd.DataFrame(
    {
        'name':['nitish','ankit','rupesh',np.nan,'mrityunjay',np.nan,'rishabh',np.nan,'aditya',np.nan],
        'college':['bit','iit','vit',np.nan,np.nan,'vlsi','ssit',np.nan,np.nan,'git'],
        'branch':['eee','it','cse',np.nan,'me','ce','civ','cse','bio',np.nan],
        'cgpa':[6.66,8.25,6.41,np.nan,5.6,9.0,7.4,10,7.4,np.nan],
        'package':[4,5,6,np.nan,6,7,8,9,np.nan,np.nan]})
students

         name college branch   cgpa  package
0      nitish     bit    eee   6.66      4.0
1       ankit     iit     it   8.25      5.0
2      rupesh     vit    cse   6.41      6.0
3         NaN     NaN    NaN    NaN      NaN
4  mrityunjay     NaN     me   5.60      6.0
5         NaN    vlsi     ce   9.00      7.0
6     rishabh    ssit    civ   7.40      8.0
7         NaN     NaN    cse  10.00      9.0
8      aditya     NaN    bio   7.40      NaN
9         NaN     git    NaN    NaN      NaN

## isnull

In [12]:
students.isnull()

    name  college  branch   cgpa  package
0  False    False   False  False    False
1  False    False   False  False    False
2  False    False   False  False    False
3   True     True    True   True     True
4  False     True   False  False    False
5   True    False   False  False    False
6  False    False   False  False    False
7   True     True   False  False    False
8  False     True   False  False     True
9   True    False    True   True     True

## notnull

In [13]:
students.notnull()

    name  college  branch   cgpa  package
0   True     True    True   True     True
1   True     True    True   True     True
2   True     True    True   True     True
3  False    False   False  False    False
4   True    False    True   True     True
5  False     True    True   True     True
6   True     True    True   True     True
7  False    False    True   True     True
8   True    False    True   True    False
9  False     True   False  False    False

## dropna(series + dataframe) - Remove missing values

In [17]:
# dropna on Series
students["name"].dropna()

0        nitish
1         ankit
2        rupesh
4    mrityunjay
6       rishabh
8        aditya
Name: name, dtype: object

In [18]:
# dropna on Dataframe
students.dropna()

      name college branch  cgpa  package
0   nitish     bit    eee  6.66      4.0
1    ankit     iit     it  8.25      5.0
2   rupesh     vit    cse  6.41      6.0
6  rishabh    ssit    civ  7.40      8.0

## fillna (series + dataframe) --> Fill Na/NaN values with value

In [ ]:
# # Replace a single value ---->  df.replace(0, np.nan)                                  Replace all 0's with NaN
# Replace multiple values with a single value ---->  df.replace([0, -2], np.nan)       Replace both 0 and -2 with NaN
# Replace Strings  ---->   df.replace({"HR": "Useless department ever to exist"})
# Replace with a dictionary ---->  df.replace({'Age': {25: 26}, 'Salary': {60000: 62000}})    Change age 25 to 26, And Salary 60000 to 62000

In [20]:
students.head()

         name college branch  cgpa  package
0      nitish     bit    eee  6.66      4.0
1       ankit     iit     it  8.25      5.0
2      rupesh     vit    cse  6.41      6.0
3         NaN     NaN    NaN   NaN      NaN
4  mrityunjay     NaN     me  5.60      6.0

In [22]:
# fillna on Series - Fill missigng values of cgpa with the avg cgpa
students["cgpa"] = students["cgpa"].fillna(students["cgpa"].mean())
students

         name college branch   cgpa  package
0      nitish     bit    eee   6.66      4.0
1       ankit     iit     it   8.25      5.0
2      rupesh     vit    cse   6.41      6.0
3         NaN     NaN    NaN   7.59      NaN
4  mrityunjay     NaN     me   5.60      6.0
5         NaN    vlsi     ce   9.00      7.0
6     rishabh    ssit    civ   7.40      8.0
7         NaN     NaN    cse  10.00      9.0
8      aditya     NaN    bio   7.40      NaN
9         NaN     git    NaN   7.59      NaN

In [23]:
# fillna on Dataframe - Replace all missing values with 0 (does not makes sense)
students.fillna(0)

         name college branch   cgpa  package
0      nitish     bit    eee   6.66      4.0
1       ankit     iit     it   8.25      5.0
2      rupesh     vit    cse   6.41      6.0
3           0       0      0   7.59      0.0
4  mrityunjay       0     me   5.60      6.0
5           0    vlsi     ce   9.00      7.0
6     rishabh    ssit    civ   7.40      8.0
7           0       0    cse  10.00      9.0
8      aditya       0    bio   7.40      0.0
9           0     git      0   7.59      0.0

## drop_duplicates (series + dataframe) --> Returns dataframe with duplicated rows removed

In [24]:
df = pd.DataFrame({
        "brand": ["Yum Yum", "Yum Yum", "Indomie", "Indomie", "Indomie"],
        "style": ["cup", "cup", "cup", "pack", "pack"],
        "rating": [4, 4, 3.5, 15, 5]})
df

     brand style  rating
0  Yum Yum   cup     4.0
1  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

In [25]:
# By default, it removes duplicate rows based on all columns
df.drop_duplicates()

# To remove duplicates based on specific column(s), use subset
# To remove duplicates and keep last occurrence, use keep

     brand style  rating
0  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

## drop --> Drop specified labels from rows or columns. Remove rows or columns by specifying label names and corresponding axis, or by directly specifying index or column names.

In [ ]:
# # Fill with a constant value ---> df.fillna(0)
# Fill with Column Specific Values ---> df.fillna({"Age": 30, "Salary": 50000})
# Fill with statistical Values --->  df["Age"].fillna(df["Age"].mean())
                                  #  df["Age"].fillna(df["Age"].median())

In [28]:
df = pd.DataFrame(np.arange(12).reshape(3, 4), columns=["A", "B", "C", "D"])
df

   A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [29]:
# Drop columns
df.drop(columns=["B", "C"], axis=1)

   A   D
0  0   3
1  4   7
2  8  11

In [31]:
# Drop row by index
df.drop([0, 1])

   A  B   C   D
2  8  9  10  11

## Apply

In [32]:
# Apply function lets you apply a custom function along a particular axis of a DataFrame
df = pd.DataFrame({
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 32, 45, 29, 41],
    'Salary': [50000, 60000, 80000, 52000, 75000],
    'Experience': [2, 7, 20, 4, 15],
    'Department': ['HR', 'IT', 'IT', 'Finance', 'HR']})
df

  Employee  Age  Salary  Experience Department
0    Alice   25   50000           2         HR
1      Bob   32   60000           7         IT
2  Charlie   45   80000          20         IT
3    David   29   52000           4    Finance
4      Eva   41   75000          15         HR

In [ ]:
# Q1 - Calculate range (max - min) for numeric columns
def give_range(salary, )
df["range"] = df.apply()