In [1]:
import numpy as np
import pandas as pd

In [4]:
course = pd.read_csv("D:/Complete DataScience/Pandas/2-Pandas/courses.csv")
deliver = pd.read_csv("D:/Complete DataScience/Pandas/2-Pandas/deliveries.csv")
match = pd.read_csv("D:/Complete DataScience/Pandas/2-Pandas/matches.csv")
reg1 = pd.read_csv("D:/Complete DataScience/Pandas/2-Pandas/reg-month1.csv")
reg2 = pd.read_csv("D:/Complete DataScience/Pandas/2-Pandas/reg-month2.csv")
student = pd.read_csv("D:/Complete DataScience/Pandas/2-Pandas/students.csv")

In [5]:
course.head()

   course_id       course_name  price
0          1            python   2499
1          2               sql   3499
2          3     data analysis   4999
3          4  machine learning   9999
4          5           tableau   2499

## pd.concat

In [11]:
# Stack reg1 and reg2 vertically
nov_dec_regs = pd.concat([reg1, reg2], ignore_index=True)
nov_dec_regs.head()

   student_id  course_id
0          23          1
1          15          5
2          18          6
3          23          4
4          16          9

# Merge

In [17]:
student.head()

   student_id            name  partner
0           1   Kailash Harjo       23
1           2     Esha Butala        1
2           3  Parveen Bhalla        3
3           4     Marlo Dugal       14
4           5     Kusum Bahri        6

In [16]:
nov_dec_regs.head()

   student_id  course_id
0          23          1
1          15          5
2          18          6
3          23          4
4          16          9

In [19]:
print(student.shape)
print(nov_dec_regs.shape)

(25, 3)
(53, 2)

In [24]:
# INNER JOIN
student.merge(right=nov_dec_regs, how="inner", on="student_id").head()

   student_id           name  partner  course_id
0           1  Kailash Harjo       23          1
1           1  Kailash Harjo       23          6
2           1  Kailash Harjo       23         10
3           1  Kailash Harjo       23          9
4           2    Esha Butala        1          5

In [25]:
# LEFT JOIN
# OUTER JOIN
# RIGHT JOIN already done before

## Q1. Find the total revenue generated

In [27]:
course.head()

   course_id       course_name  price
0          1            python   2499
1          2               sql   3499
2          3     data analysis   4999
3          4  machine learning   9999
4          5           tableau   2499

In [31]:
total_revenue = nov_dec_regs.merge(course, how="inner", on="course_id")["price"].sum()
print(total_revenue)

154247

## Q2. Print the registration table