In [3]:
import numpy as np
import pandas as pd

In [4]:
car1 = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv")
car2 = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv")

In [5]:
car1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN

In [6]:
car2.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,33.0,4,91,53,1795,17.4,76,3,honda civic
1,20.0,6,225,100,3651,17.7,76,1,dodge aspen se
2,18.0,6,250,78,3574,21.0,76,1,ford granada ghia
3,18.5,6,250,110,3645,16.2,76,1,pontiac ventura sj
4,17.5,6,258,95,3193,17.8,76,1,amc pacer d/l

In [11]:
# Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1
car1 = car1.loc[:, "mpg":"car"]
car1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

In [12]:
# Step 5: What is the number of observations in each dataset?
print(f"Rows in car1: {car1.shape[0]}")
print(f"Rows in car2: {car2.shape[0]}")

Rows in car1: 198
Rows in car2: 200

In [17]:
# Step 6: Join cars1 and cars2 into a single DataFrame called cars
cars = pd.concat([car1, car2], axis=0)
cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

In [22]:
# Step 7: Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.
owners = pd.Series(np.random.randint(low=15000, high=73001, size=car1.shape[0]+car2.shape[0]))
owners

0      67046
1      28288
2      28366
3      23039
4      22636
       ...
393    53062
394    53347
395    23671
396    69778
397    66044
Length: 398, dtype: int32

In [23]:
# Step 8. Add the column owners to cars
cars["owners"] = owners

In [24]:
cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,67046
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,28288
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,28366
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,23039
4,17.0,8,302,140,3449,10.5,70,1,ford torino,22636