In [32]:
import pandas as pd
import datetime as dt

In [33]:
data = {
    "order_id": [1, 2, 3, 4, 5],
    "order_date": ['2024-01-15', '2024-03-22', '2024-07-04', '2024-11-28', '2024-12-31']
}

df = pd.DataFrame(data)
df["order_date"] = pd.to_datetime(df["order_date"])

In [34]:
df

   order_id order_date
0         1 2024-01-15
1         2 2024-03-22
2         3 2024-07-04
3         4 2024-11-28
4         5 2024-12-31

In [35]:
# Year
df["year"] = df["order_date"].dt.year
df

   order_id order_date  year
0         1 2024-01-15  2024
1         2 2024-03-22  2024
2         3 2024-07-04  2024
3         4 2024-11-28  2024
4         5 2024-12-31  2024

In [36]:
# Month
df["month"] = df["order_date"].dt.month
df

   order_id order_date  year  month
0         1 2024-01-15  2024      1
1         2 2024-03-22  2024      3
2         3 2024-07-04  2024      7
3         4 2024-11-28  2024     11
4         5 2024-12-31  2024     12

In [37]:
# Day
df["day"] = df["order_date"].dt.day
df

   order_id order_date  year  month  day
0         1 2024-01-15  2024      1   15
1         2 2024-03-22  2024      3   22
2         3 2024-07-04  2024      7    4
3         4 2024-11-28  2024     11   28
4         5 2024-12-31  2024     12   31

In [38]:
# Weekday
df["weekday"] = df["order_date"].dt.weekday
df

   order_id order_date  year  month  day  weekday
0         1 2024-01-15  2024      1   15        0
1         2 2024-03-22  2024      3   22        4
2         3 2024-07-04  2024      7    4        3
3         4 2024-11-28  2024     11   28        3
4         5 2024-12-31  2024     12   31        1

In [39]:
# Quarter
df["quarter"] = df["order_date"].dt.quarter
df

   order_id order_date  year  month  day  weekday  quarter
0         1 2024-01-15  2024      1   15        0        1
1         2 2024-03-22  2024      3   22        4        1
2         3 2024-07-04  2024      7    4        3        3
3         4 2024-11-28  2024     11   28        3        4
4         5 2024-12-31  2024     12   31        1        4

In [40]:
# is_weekend
df["is_weekend"] = df["order_date"].dt.weekday.isin([5, 6]).astype(int)
df

   order_id order_date  year  month  day  weekday  quarter  is_weekend
0         1 2024-01-15  2024      1   15        0        1           0
1         2 2024-03-22  2024      3   22        4        1           0
2         3 2024-07-04  2024      7    4        3        3           0
3         4 2024-11-28  2024     11   28        3        4           0
4         5 2024-12-31  2024     12   31        1        4           0

In [41]:
# is_month_end
df["is_month_end"] = df["order_date"].dt.day.isin([27, 28, 29, 30, 31]).astype(int)
df

,order_id,order_date,year,month,day,weekday,quarter,is_weekend,is_month_end
0,1,2024-01-15,2024,1,15,0,1,0,0
1,2,2024-03-22,2024,3,22,4,1,0,0
2,3,2024-07-04,2024,7,4,3,3,0,0
3,4,2024-11-28,2024,11,28,3,4,0,1
4,5,2024-12-31,2024,12,31,1,4,0,1

In [43]:
# day_name
df["day_name"] = df["order_date"].dt.day_name()
df

,order_id,order_date,year,month,day,weekday,quarter,is_weekend,is_month_end,day_name
0,1,2024-01-15,2024,1,15,0,1,0,0,Monday
1,2,2024-03-22,2024,3,22,4,1,0,0,Friday
2,3,2024-07-04,2024,7,4,3,3,0,0,Thursday
3,4,2024-11-28,2024,11,28,3,4,0,1,Thursday
4,5,2024-12-31,2024,12,31,1,4,0,1,Tuesday

### Questions:

##### 1- Which orders are on weekends? None of them are on weekends.
##### 2- Which were in Q4? Order_id 4 and 5
##### 3- Which were on the end of month? Order_id 4 and 5