In [1]:
import numpy as np
import pandas as pd
import datetime as dt

In [2]:
df = pd.DataFrame({
    'date': pd.date_range(start='2024-01-01', periods=10, freq='D'),
    'sales': [200, 220, 180, 240, 210, 260, 230, 250, 270, 290]})

df

        date  sales
0 2024-01-01    200
1 2024-01-02    220
2 2024-01-03    180
3 2024-01-04    240
4 2024-01-05    210
5 2024-01-06    260
6 2024-01-07    230
7 2024-01-08    250
8 2024-01-09    270
9 2024-01-10    290

In [6]:
# Sales_rolling _mean_3
df["sales_rolling_mean_3"] = df["sales"].rolling(window=3).mean()
df

        date  sales  sales_rolling_mean_3
0 2024-01-01    200                   NaN
1 2024-01-02    220                   NaN
2 2024-01-03    180            200.000000
3 2024-01-04    240            213.333333
4 2024-01-05    210            210.000000
5 2024-01-06    260            236.666667
6 2024-01-07    230            233.333333
7 2024-01-08    250            246.666667
8 2024-01-09    270            250.000000
9 2024-01-10    290            270.000000

In [7]:
# sales_rolling_mean_5
df["sales_rolling_mean_5"] = df["sales"].rolling(window=5).mean()
df

        date  sales  sales_rolling_mean_3  sales_rolling_mean_5
0 2024-01-01    200                   NaN                   NaN
1 2024-01-02    220                   NaN                   NaN
2 2024-01-03    180            200.000000                   NaN
3 2024-01-04    240            213.333333                   NaN
4 2024-01-05    210            210.000000                 210.0
5 2024-01-06    260            236.666667                 222.0
6 2024-01-07    230            233.333333                 224.0
7 2024-01-08    250            246.666667                 238.0
8 2024-01-09    270            250.000000                 244.0
9 2024-01-10    290            270.000000                 260.0

In [8]:
# sales_rolling_sum_3
df["sales_rolling_sum_3"] = df["sales"].rolling(window=3).sum()
df

,date,sales,sales_rolling_mean_3,sales_rolling_mean_5,sales_rolling_sum_3
0,2024-01-01,200,NaN,NaN,NaN
1,2024-01-02,220,NaN,NaN,NaN
2,2024-01-03,180,200.000000,NaN,600.0
3,2024-01-04,240,213.333333,NaN,640.0
4,2024-01-05,210,210.000000,210.0,630.0
5,2024-01-06,260,236.666667,222.0,710.0
6,2024-01-07,230,233.333333,224.0,700.0
7,2024-01-08,250,246.666667,238.0,740.0
8,2024-01-09,270,250.000000,244.0,750.0
9,2024-01-10,290,270.000000,260.0,810.0